package perror



const (
  ERROR_DIRECTORY_NOT_EXIST = iota + 0x1000
  ERROR_FILESYSTEM
  ERROR_LOGCONFIG
  ERROR_FAILED_TO_CREATE_DIRECTORY
  ERROR_INTERNAL
  ERROR_CONFIG_READ
  ERROR_CONFIG_SAVE
  ERROR_CONFIG_PARSE
  ERROR_RAIDA_QUORUM
  ERROR_TASK_NOT_FOUND
  ERROR_TASK_TIMEOUT

  ERROR_PARAMS_TASKID_MISSING
  ERROR_PARAMS_WALLET_NAME_MISSING
  ERROR_ENCODE_OUTPUT_JSON
  ERROR_DECODE_INPUT_JSON

  ERROR_STORAGE_DRIVER_NOT_FOUND
  ERROR_STORAGE_DRIVER_INIT
  ERROR_FS_DRIVER_FAILED_TO_READ_FOLDER

  ERROR_WALLET_ALREADY_EXISTS
  ERROR_WALLET_NOT_FOUND
  ERROR_WALLET_NOT_EMPTY
  ERROR_DELETE_WALLET
  ERROR_FAILED_TO_CREATE_WALLET
  ERROR_USER_HOMEDIR_NOT_FOUND


  ERROR_DECODE_HEX
  ERROR_VALIDATE


  ERROR_DECODE_BASE64
  ERROR_UNPACK


  ERROR_UNPACKER_NOT_MATCH
  ERROR_NO_CLOUDCOINS_IN_STACK
  ERROR_PNG_SIGNATURE

  ERROR_IMPORT
  ERROR_COIN_ALREADY_EXISTS
  ERROR_SAVE_COIN
  ERROR_COIN_INVALID_LOCATION
  ERROR_REMOVE_FILE

  ERROR_FAILED_TO_UPDATE_WALLET_CONTENTS

  ERROR_INVALID_LOCATION

  ERROR_FAILED_TO_PICK_COINS
  ERROR_NOT_ENOUGH_COINS
  ERROR_MISSING_DENOMINATION

  ERROR_INVALID_POWNSTRING


  ERROR_INVALID_HEADER_SIZE
  ERROR_INVALID_COIN_BODY_SIZE


  ERROR_UNSUPPORTED_ENCRYPTION_TYPE 
  ERROR_UNSUPPORTED_COIN_CLOUDID
  ERROR_UNSUPPORTED_COIN_ID1
  ERROR_UNSUPPORTED_COIN_ID2
  ERROR_UNSUPPORTED_COIN_FORMAT_TYPE

  ERROR_INVALID_SERIAL_NUMBER

  ERROR_READING_COIN


  ERROR_FAILED_TO_DRAW_FILE
  ERROR_UNSUPPORTED_FILE_TYPE

  ERROR_SN_MISMATCH

  ERROR_INVALID_PNG_HEADER
  ERROR_FAILED_TO_BREAK_COIN
  ERROR_FAILED_TO_FIND_COIN_TO_BREAK
  ERROR_EMPTY_CHANGE_SERVER

  ERROR_SERVICE_NOT_FOUND
  ERROR_WALLET_CONFIG_PARSE
  ERROR_UPDATE_COIN_STATUS

  ERROR_GENERATE_RANDOM
  ERROR_SAVE_TRANSACTION
  ERROR_READ_TRANSACTIONS
  ERROR_UNZIP
  ERROR_FAILED_TO_MOVE_COINS

  ERROR_INVALID_EXPORT_TYPE
  ERROR_ZIP

  ERROR_HTTP_REQUEST
  ERROR_GUARDIANS
  ERROR_GUARDIAN_PARSE
  ERROR_RAIDA_UNAVAILABLE

  ERROR_INVALID_DENOMINATION
  ERROR_COLLECTING_COINS_FROM_CHANGE
  ERROR_PARSE_FEED

  ERROR_FREECOIN_ATTEMPTS_REACHED
  ERROR_NO_SKYWALLET_NAME

  ERROR_DNS_RECORD_EXISTS
  ERROR_DNS_SERVICE_CONNECT

  ERROR_PICKING_RANDOM_RAIDA

  ERROR_GET_TICKET
  ERROR_PARSE_DNS_RESPONSE
  ERROR_DNS_SERVICE_RESPONSE
  ERROR_INVALID_IP
  ERROR_TOO_MANY_IPS

  ERROR_COIN_COUTERFEIT

  ERROR_DNS_RESOLVE

  ERROR_SAVE_SETTINGS
  ERROR_LOAD_SETTINGS

  ERROR_LISTEN

  ERROR_GET_BALANCE
  ERROR_MEMO_TOO_LONG

  ERROR_ASSEMBLE_STRIPE_MIRRORS

  ERROR_COMMAND_LINE_ARGUMENTS
  ERROR_COMMAND_NOT_FOUND

  ERROR_FAILED_TO_FIX

  ERROR_NO_COINS

  ERROR_BACKUP_FOLDER
  ERROR_FAILED_TO_DELETE_ALL_STATEMENTS
  ERROR_WRITE_FILE
  ERROR_READ_RECEIPT
  ERROR_RECEIPT_NOT_EXISTS
  ERROR_DELETE_TRANSACTIONS
  ERROR_DELETE_RECEIPTS
  ERROR_RENAME_WALLET

  ERROR_DIALOG_CANCELLED
  ERROR_FILE_PICK

  ERROR_ADD_SENDER_HISTORY
  ERROR_GET_SENDER_HISTORY

  ERROR_INVALID_REGEX
  ERROR_DRAW_PNG
  ERROR_HTTP_NEWSFEED

  ERROR_MIX_SUSPECT_WITH_OTHERS

)
